services:
  db:
    images: sqlite
    volumes:
      - ./db:/var/lib/sqlite
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: password
